site_name: Splice Horizon — Orivay Canon
theme:
  name: material
nav:
  - Home: index.md
  - Canon:
      - World Bible: canon/world_bible.md
      - Charter Articles: canon/charter_articles.md
      - Selection Mechanics: canon/selection_mechanics.md
      - Season Outline: canon/season_outline.md
      - Style Guide: canon/style_guide.md
      - Audio Rules: canon/audio_rules.md
      - Timeline: canon/timeline.md
  - Characters:
      - Dr. Elias Tharros: characters/elias_tharros.md
      - Liora Veylin: characters/liora_veylin.md
      - Kaela Tharros: characters/kaela_tharros.md
      - Joren Calrix: characters/joren_calrix.md
      - Mira Jeylan: characters/mira_jeylan.md
      - Rhea Halden: characters/rhea_halden.md
      - Captain Rourke Draeven: characters/rourke_draeven.md
      - Nyra Solwyn: characters/nyra_solwyn.md
      - Dax Morlin: characters/dax_morlin.md
      - Commander Aric Veynar: characters/aric_veynar.md
      - Councillor Hollis Venner: characters/hollis_venner.md
      - Councillor Kaldor Mirea: characters/kaldor_mirea.md
      - Clerk Evan Trusell: characters/evan_trusell.md
      - Director Amaris Colvern: characters/amaris_colvern.md
  - Weapons:
      - Primer: weapons/primer.md
      - Restricted, Dax: weapons/restricted_dax.md
  - Episodes:
      - Template: episodes/templates/episode_template.md
  # BEGIN AUTO-EPISODES
  - Episodes:
      - Chapter 1: episodes/ch01/draft.md
      - Chapter 2: episodes/ch02/draft.md
      - Chapter 3: episodes/ch03/draft.md
      - Chapter 4: episodes/ch04/draft.md
      - Chapter 5: episodes/ch05/draft.md
      - Chapter 6: episodes/ch06/draft.md
      - Chapter 7: episodes/ch07/draft.md
      - Chapter 8: episodes/ch08/draft.md
  # END AUTO-EPISODES
