name: Lint audio rules

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Lint chapter drafts only
        shell: bash
        run: |
          set -e
          files="$(git ls-files 'docs/episodes/ch??/draft.md' || true)"
          if [ -z "$files" ]; then
            echo "No chapter drafts found; skipping linter."
            exit 0
          fi
          python tools/lint_audio.py $files
